"""Agent prompts and templates."""

from .prompt_builder import PromptBuilder
from .templates import (
    AGENT_IDENTITY_OPENING,
    ENVIRONMENT_SECTION,
    EXECUTION_CONSTRAINTS_SECTION,
    IDENTITY_SECTION,
    IMPORTANT_DIRECT_REPLY,
    PROTOCOL_AND_FORMAT,
    SKILLS_SECTION,
    SUMMARIZE_CONVERSATION_PROMPT,
)

__all__ = [
    "AGENT_IDENTITY_OPENING",
    "ENVIRONMENT_SECTION",
    "EXECUTION_CONSTRAINTS_SECTION",
    "IDENTITY_SECTION",
    "IMPORTANT_DIRECT_REPLY",
    "PromptBuilder",
    "PROTOCOL_AND_FORMAT",
    "SKILLS_SECTION",
    "SUMMARIZE_CONVERSATION_PROMPT",
]
